In [3]:
import numpy as np

array = np.random.randint(1,10, size=(10,3))

display(array)

print(array)


array([[1, 6, 7],
       [3, 2, 3],
       [6, 2, 4],
       [9, 1, 7],
       [4, 2, 1],
       [1, 7, 3],
       [3, 3, 2],
       [6, 1, 5],
       [4, 3, 4],
       [9, 9, 6]])

[[1 6 7]
 [3 2 3]
 [6 2 4]
 [9 1 7]
 [4 2 1]
 [1 7 3]
 [3 3 2]
 [6 1 5]
 [4 3 4]
 [9 9 6]]
